### PR TITLE
Filenames update

### PR DESCRIPTION
**Pull request by RandomTBush**
I've added a few more filenames and one more static object (RollSwitch / BD7B0128A038883FE438A56FF8225BA8).

(Apologies if I'm doing something wrong, I've never Git'd before.)

### CODE REVIEW

**Comment by NWPlayer123** [comment]
I can add one more from my list that isn't in this latest version:
['4CA13A4EC1C3E760C57E13D4D620F011', 'Data/Sprites/Eggman/EggmanGHZCutt.gif']

**Comment by RandomTBush** [comment]
@NWPlayer123 Already taken care of in the pull request.

**Comment by koolkdev** [comment]
Thanks. 16 of them were missing in my file. So now we are down to 50 missing. I didn't merge this because I added only the missing 16, (sorted by lexicographically order)

**Comment by RandomTBush** [comment]
@koolkdev That's fine! The important thing was that you were able to get the new files added to the list. I'll be sure to do a proper revision next time if I happen to find any more of 'em.

**Comment by RagdollClash** [comment]
Thanks to the unknown decryptions, I was able to find a few more file names.

```
Data/Sprites/Editor/CutsceneHBH.bin
Data/Sprites/Editor/CutsceneHBH.gif
Data/Sprites/Editor/Icons.gif
Data/Sprites/UI/PauseEN_old.gif
Data/Sprites/UI/TextEN_old.bin
Data/Sprites/UI/TextEN_old.gif
```

**Comment by koolkdev** [comment]
We did the same things :) I also added few files from Data/Stages.

**Comment by RagdollClash** [comment]
Good to know that we're slowly getting towards getting all the file names found. I think the most tricky thing would be figuring out how to get the PNG file name.

**Comment by RandomTBush** [comment]
@koolkdev Found nine more:

> Data/Sprites/Editor/EditorIcons.bin
Data/Sprites/Editor/PlayerIcons.bin
Data/Sprites/PSZ1/Enemies-Temp.gif
Data/Sprites/PSZ1/Enemies-Old.gif
Data/Sprites/PSZ2/Enemies-Temp.gif
Data/Sprites/UI/SaveSelect_old.gif
Data/Stages/DAGarden/16x16Tiles.gif
Data/Stages/DAGarden/Scene1.bin
Data/Stages/DAGarden/StageConfig.bin

**Comment by koolkdev** [comment]
Thanks! I found few more, now we are down to ~~17~~ 13 lefts:
~~2~~ 1 static objects file (edit: actually I am not sure if the one that left is a static object file, it is too small to say what it is)
2 unknown files
4 meshes
~~4~~ 2 sprite gifs
1 sprite binary (should be in data/sprites/lrz1)
1 wav
~~1~~ 0 png
2 scene files (on related to msz, and anoother to spz1)

**Comment by RandomTBush** [comment]
I'm guessing that the two scene files are related to the demo version's Studiopolis Act 1 and Mirage Saloon Act 2, which has the signpost right before where the bosses would be, so trying Scene* name setups for those two zones would probably work (similarly to how you figured out the ending scene filenames).

One of the two sprite files is yet another variant of the Press Garden enemies sheet (namely PSZ1/Enemies-old.gif), but the few names I tried didn't come up with anything. 

Not sure about the rest yet, but I'll keep experimenting (though someone else is bound to find it before I do). We're so close now!

**Comment by koolkdev** [comment]
The MSZ scene is the Knukle exclusive MSZ Act 1.
But since I haven't play this game yet I can't seem to be able to access it without playing thru. But if you can access this level, you can repack the Data.rsdk without this file (delete .unknown/082c529920f4db792c5692402b729650 before repacking)
and than run the game with 'SonicMania.exe "console=true;"'. It should print to the console when it fails to open the scene file with its path.

The SPZ1 scene seems to be another version of SPZ Act 1.

**Comment by RandomTBush** [comment]
@koolkdev Well, I'm stupid, I should've realized that! Plus, I figured out the other SPZ file:

Data/Stages/MSZ/Scene1K.bin
Data/Stages/SPZ1/Scene1D.bin

Anyway, I also noticed how the unknown MDL files are four (out of five/six?) parts for a Death Egg model (body, moustache, middle 1 and middle 2, with the eyes and nose being missing)... or is it a 3D version of the DD Wrecker from GHZ?

**Comment by koolkdev** [comment]
oh, you made me realize that I was trying to find files in data/stage/ today instead data/stages. This is why I didn't find it. I found the second one data/stages/spz1/scene1d.bin*

**Comment by RandomTBush** [comment]
Updated my post above, figure out the SPZ file too!

**Comment by koolkdev** [comment]
It is indeed looks like DDWrecker. But I failed to find mesh bin file with ddwrecker/wrecker in it. So it is more probable that it is part of death egg? (and I copied the wrong string to my previous comment :) )

**Comment by RandomTBush** [comment]
Heh, so it looks like we'd figured that out at the same time, then!

But yeah, makes me wonder if one of the still-encrypted files could be the missing pieces for that, then?

**Comment by koolkdev** [comment]
45a96bf5cb9bf252e79d3f63cdb9a86f and d3cb232af70d4c4681514f3c5a5d8406 does look like possible meshes. I will try to decrypt them with this knowledge.

**Comment by koolkdev** [comment]
ok, 45a96bf5cb9bf252e79d3f63cdb9a86f is really mdl. And you were right, it is his eyes and nose! the second one isn't mdl. so this was the last mdl.

**Comment by RandomTBush** [comment]
Two more!

> Data/Sprites/Blank/Objects.gif
> Data/Sprites/Blank/Platform.bin

The latter takes care of the encrypted "0eb29a7d7214216dc7f217a4dc588786" file.

**Comment by NWPlayer123** [comment]
question, how is your math adding up in the Readme @koolkdev cause the file list is 1604 lines and the key list is 47 which only gets up to 1651, not 1664

**Comment by RandomTBush** [comment]
@NWPlayer123 That's what the static_objects_list file is for.

(EDIT: Parsing the animation data, it looks like the unknown sprite binary is a variant on the "BuckwildBall" file, except with additional rock particles.)

(EDIT 2: Perhaps this would help with trying to figure out the remaining files. Thinking out loud, judging by where the hashes are located...)

> d3cb232af70d4c4681514f3c5a5d8406
Between Data/Game/GameConfig.bin and Data/Meshes/Continue/Count0.bin. Last unknown encrypted file, could be a second one in the Game folder?

> 7fc17d4fd87751bd80a0e97f3eb3b647
> 45a96bf5cb9bf252e79d3f63cdb9a86f
> 434d1548870a80584cebfdfd4b232b37
> 898ff3a512bd541377ffe1c0863684e7
> 31dc80f94c09d8deb9de49e65c138bb2
Between Data/Meshes/Decoration/Tree.bin and Data/Meshes/Global/Sonic.bin. These five are for the DD Wrecker model, most likely in Data/Meshes/GHZ/.

> 3465d2cf44eb0a1c10cc0cfedc98278c
Between Data/SoundFX/MSZ/Pinata.wav and Data/SoundFX/MSZ/SandFall.wav. Last sound effect relating to Mirage Saloon?

> ea7b0ce95e010e53724320faff39c70f
Between Data/Sprites/LRZ1/Fireworm.bin and Data/Sprites/LRZ1/Iwamodoki.bin. Last sprite binary,  related to the BuckwildBall as mentioned above.

> bb690e6627c6a2a86bd58434a26aa292
Between Data/Sprites/PSZ2/Dragonfly.bin and Data/Sprites/PSZ2/Enemies-Temp.gif. This is the last sprite file for the *alternate* alternate PSZ enemies.

**Comment by MainMemory** [comment]
I don't know if it'll help, but I've written a DLL that you can place in Sonic Mania's folder that will log every unique file path the game loads to files.txt.
[d3d9.zip](https://github.com/koolkdev/rsdkv5_extract/files/1272273/d3d9.zip)

**Comment by RandomTBush** [comment]
@MainMemory Unfortunately what we're dealing with now might all be unused stuff, so I'm not sure if that'll work.

Nice work, though! 👍

**Comment by MainMemory** [comment]
Yeah, I figured as much, given how many files have been documented already.

**Comment by AdrianNinja** [comment]
Anyone know how to pack the data file? I've been dragging the data folder into the pack exe and nothing is happening.

**Comment by RagdollClash** [comment]
@AdrianNinja I'd use [MainMemory's Mod Loader](http://forums.sonicretro.org/index.php?showtopic=37160) for testing file edits.

**Comment by RagdollClash** [comment]
They added new languages in the latest patch, in case you were not aware. Time for more file finding.

**Comment by RandomTBush** [comment]
@slashiee No need, actually, as all of the files already existed in the game before the patch!
> Data/Sprites/UI/HeadingsKO.gif
Data/Sprites/UI/HeadingsKO.bin
Data/Sprites/UI/HeadingsSC.gif
Data/Sprites/UI/HeadingsSC.bin
Data/Sprites/UI/HeadingsTC.gif
Data/Sprites/UI/HeadingsTC.bin
Data/Sprites/UI/PauseKO.gif
Data/Sprites/UI/PauseSC.gif
Data/Sprites/UI/PauseTC.gif
Data/Sprites/UI/TextKO.bin
Data/Sprites/UI/TextKO.gif
Data/Sprites/UI/TextSC.bin
Data/Sprites/UI/TextSC.gif
Data/Sprites/UI/TextTC.bin
Data/Sprites/UI/TextTC.gif
Data/Strings/StringsKO.txt
Data/Strings/StringsSC.txt
Data/Strings/StringsTC.txt
>

**Comment by RagdollClash** [comment]
oh. Wonder why they didn't add them until now...

**Comment by RandomTBush** [comment]
@slashiee Judging by the fact that most of those were modified in one way or another in the latest patch, I'm pretty sure it's because they hadn't been proofread yet.

**Pull request closed without merging**
